name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  releasenew:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install Dependencies
      run: npm ci --no-fund --no-audit
    - name: Build main with VitePress
      run: |
        npm run -w main docs:build
