name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  dovecot:
    runs-on: ubuntu-latest
    environment: dovecot
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - name: Install Dependencies
      run: npm ci --no-fund --no-audit
    - name: Build dovecot.org with Sveltekit
      run: |
        npm run -w main build
    - name: Deploy
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr --delete
        HOST: ${{ env.HOST }}
        USER: website
        LOCALPATH: /main/build/.
        REMOTEPATH: ${{ env.REMOTEPATH }}/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY && env.HOST && env.REMOTEPATH
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: ${{ vars.HOST }}
        REMOTEPATH: ${{ vars.REMOTEPATH }}

  pigeonhole:
    runs-on: ubuntu-latest
    environment: pigeonhole
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - name: Install Dependencies
      run: npm ci --no-fund --no-audit
    - name: Build pigeonhole with Sveltekit
      run: |
        npm run -w pigeonhole build
    - name: Deploy
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr --delete
        HOST: ${{ env.HOST }}
        USER: website
        LOCALPATH: /pigeonhole/build/.
        REMOTEPATH: ${{ env.REMOTEPATH }}/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY && env.HOST && env.REMOTEPATH
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: ${{ vars.HOST }}
        REMOTEPATH: ${{ vars.REMOTEPATH }}

  repo:
    runs-on: ubuntu-latest
    environment: repo
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Deploy
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr
        HOST: ${{ env.HOST }}
        USER: website
        LOCALPATH: /repo/.
        REMOTEPATH: ${{ env.REMOTEPATH }}/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY && env.HOST && env.REMOTEPATH
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: ${{ vars.HOST }}
        REMOTEPATH: ${{ vars.REMOTEPATH }}
