name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  releasenew:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install Dependencies
      run: npm ci --no-fund --no-audit
    - name: Build dovecot.org with VitePress
      run: |
        npm run -w main docs:build
    - name: Build repo.dovecot.org with VitePress
      run: |
        npm run -w repo docs:build
    - name: Build pigeonhole with VitePress
      run: |
        npm run -w pigeonhole docs:build
    - name: Deploy dovecot.org
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr --delete
        HOST: dovecot.org
        USER: website
        LOCALPATH: /main/.vitepress/dist/.
        REMOTEPATH: public_html/main/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy repo.dovecot.org
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr --delete
        HOST: repo.dovecot.org
        USER: website
        LOCALPATH: /repo/.vitepress/dist/.
        REMOTEPATH: public_html/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy pigeonhole.dovecot.org
      uses: dovecot/rsync-deployments@v2.0.3
      with:
        FLAGS: -azr --delete
        HOST: pigeonhole.dovecot.org
        USER: website
        LOCALPATH: /pigeonhole/.vitepress/dist/.
        REMOTEPATH: public_html/pigeonhole/${{ github.ref_name }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: env.DEPLOY_KEY
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
